{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "linguagap.fullname" . }}-websocket
  labels:
    {{- include "linguagap.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      Connection: "keep-alive, Upgrade"
      Upgrade: "WebSocket"
{{- end }}
