{{- if and .Values.secrets.hfToken.enabled .Values.secrets.hfToken.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.hfToken.secretName }}
  labels:
    {{- include "linguagap.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.hfToken.secretKey }}: {{ .Values.secrets.hfToken.value | quote }}
{{- end }}
